-- MySQL Script generated by MySQL Workbench
-- Wed Jan 17 12:17:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALId_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema brewery
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `brewery` ;

-- -----------------------------------------------------
-- Schema brewery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brewery` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `brewery` ;

-- -----------------------------------------------------
-- Table `Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `role` (
  `roleId` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roleId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `employee` (
  `empId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(30) NOT NULL UNIQUE,
  `roleId` INT NOT NULL,
  `isActive` TINYINT NOT NULL,
  `resetPasswordUUID` VARCHAR(50),
    
  PRIMARY KEY (`empId`))
ENGINE = InnoDB;

SHOW WARNINGS;



-- -----------------------------------------------------
-- Table `SV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sv` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sv` (
  `svId` INT NOT NULL AUTO_INCREMENT,
  `capacity` INT NOT NULL,
  `volume` DOUBLE NULL,
    `brew1` INT NULL,
    `brew2` INT NULL,
    `brew3` INT NULL,
    `brand` VARCHAR(15) NULL,
  `status` CHAR NULL,
  PRIMARY KEY (`svId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Production`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `production` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `production` (
  `prodId` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `employeeId` INT NOT NULL,
  `svNum` INT NOT NULL,
  `productionType` VARCHAR(20) NOT NULL,
  `expectedSvVolume` DOUBLE NOT NULL,  
  `finishedSvVolume` DOUBLE NOT NULL,
  `gainLoss` DOUBLE NOT NULL,
  PRIMARY KEY (`prodId`))
ENGINE = InnoDB;

SHOW WARNINGS;
-- -----------------------------------------------------
-- Table `ProductionMaterial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productionmaterial` ;

CREATE TABLE IF NOT EXISTS `productionmaterial` (
  `Name` VARCHAR(50) NOT NULL,
  `qty` INT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;

SHOW WARNINGS;
-- -----------------------------------------------------
-- Table `ProductionMaterialUsage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productionmaterialssage` ;

CREATE TABLE IF NOT EXISTS `productionmaterialusage` (
  `materialQty` INT NULL,
  `name` VARCHAR(50) NOT NULL,
  `productionusage` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`productionusage`, `name`))
ENGINE = InnoDB;

SHOW WARNINGS;
-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `account` (
  `companyName` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`companyName`, `address`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `FinishedProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finishedproduct` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `finishedproduct` (
  `productName` VARCHAR(40) NOT NULL,
  `qty` INT NULL,
  `volumePerUnit` DOUBLE NOT NULL,
  PRIMARY KEY (`productName`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `product` (
  `productName` VARCHAR(45) NOT NULL,
  `qty` INT NOT NULL,
  `deliveryId` INT NOT NULL,
  PRIMARY KEY (`deliveryId`, `productName`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `delivery` (
  `deliveryId` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `companyName` VARCHAR(45) NOT NULL,
  `empId` INT NOT NULL,
  PRIMARY KEY (`deliveryId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `FV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fv` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fv` (
  `fvId` INT NOT NULL AUTO_INCREMENT,
  `capacity` INT NOT NULL,
  `volume` DOUBLE NULL,
    `brew1` INT NULL,
    `brew2` INT NULL,
    `brew3` INT NULL,
    `brand` VARCHAR(15) NULL,
  `status` CHAR NULL,
  PRIMARY KEY (`fvId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recipe` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `recipe` (
  `recipeName` VARCHAR(25) NOT NULL,
  `dateModified` DATE NULL,
  `mashInTemp` FLOAT NULL,
  `mashInTime` FLOAT NULL,
  `mashWaterVolume` INT NULL,
  `restTime` DECIMAL NULL,
  `raiseToTemp` INT NULL,
  `inTime` DECIMAL NULL,
  `totalMashTime` DECIMAL NULL,
  `underletLitres` INT NULL,
  `rest` DECIMAL NULL,
  `vorlaufTime` DECIMAL NULL,
  `firstWortGrav` FLOAT NULL,
  `runOffTime` DECIMAL NULL,
  `spargVol` DECIMAL NULL,
  `spargTemp` FLOAT NULL,
  `lastRunningsGrav` FLOAT NULL,
  `kettleFullVol` DECIMAL NULL,
  `kettleFullGrav` FLOAT NULL,
  `boilTime` DECIMAL NULL,
  `strikeOutVol` DECIMAL NULL,
  `strikeOutGrav` FLOAT NULL,
  `whirlPoolTime` DECIMAL NULL,
  `coolInTemp` FLOAT NULL,
  `oxygenRate` FLOAT NULL,
  `gypsumAmt` FLOAT NULL,
  `calciumChlorideAmt` FLOAT NULL,
  `sodiumChlorideAmt` FLOAT NULL,
  `phosphAcidAmt` FLOAT NULL,
  `firstHop` VARCHAR(20) NULL,
  `firstHopAmt` FLOAT NULL,
  `secondHop` VARCHAR(20) NULL,
  `secondHopAmt` FLOAT NULL,
  `thirdHop` VARCHAR(20) NULL,
  `thirdHopAmt` FLOAT NULL,
  `baseMalt` VARCHAR(20) NULL,
  `baseMaltAmt` FLOAT NULL,
  `secondMalt` VARCHAR(20) NULL,
  `secondMaltAmt` FLOAT NULL,
  `thirdMalt` VARCHAR(20) NULL,
  `thirdMaltAmt` FLOAT NULL,
  `fourthMalt` VARCHAR(20) NULL,
  `fourthMaltAmt` FLOAT NULL,
  PRIMARY KEY (`recipeName`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Brew`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brew` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `brew` (
  `brewId` INT NOT NULL AUTO_INCREMENT,
  `date` DATE,  
  `mashInTime` FLOAT NULL,
  `restTime` FLOAT NULL,
  `inTime` FLOAT NULL,
  `totalMashTime` FLOAT NULL,  
  `underletTime` FLOAT NULL,
  `lauterRestTime` FLOAT NULL,
  `vorlaufTime` FLOAT NULL,
  `firstWortGravity` FLOAT NULL,
  `runOffTime` FLOAT NULL,
  `lastRunningsGravity` FLOAT NULL,
  `kettleFullVol` FLOAT NULL,
  `kettleFullGravity` FLOAT NULL,
  `kettleStrikeOutVol` FLOAT NULL,
  `kettleStrikeOutGravity` FLOAT NULL,
  `allInVolume` FLOAT NULL,  
  `empId` INT NOT NULL,
  `fvId` INT NOT NULL,
  `recipeName` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`brewId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supplier` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `supplier` (
  `supplierId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`supplierId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PurchaseOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `purchaseorder` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `purchaseorder` (
  `purchaseOrderId` INT NOT NULL,
  `materialId` INT NULL,
  `qty` INT NULL,
  `empId` INT NOT NULL,
  `supplierId` INT NOT NULL,
  `dateArrived` DATE NULL,
  PRIMARY KEY (`purchaseOrderId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `BrewMaterials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brewmaterials` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `brewmaterials` (
  `name` VARCHAR(25) NOT NULL,
  `qty` double NULL,
  `units` VARCHAR(5) NULL,
  `type`  VARCHAR(10) NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `RecipeMaterials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recipematerials` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `recipematerials` (
  `qty` double NULL,
  `recipeName` VARCHAR(25) NOT NULL,
  `brewMaterialsName` VARCHAR(15) NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transfer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `transfer` (
  `transferId` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `volume` DOUBLE NULL,
  `fromFv` INT NOT NULL,
  `toSv` INT NOT NULL,
  `brand` VARCHAR(15) NULL,
  `correction` DOUBLE NULL,
  PRIMARY KEY (`transferId`))
ENGINE = InnoDB;

SHOW WARNINGS;
USE `brewery` ;

-- -----------------------------------------------------
-- Table `ProductionSchedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productionschedule` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `productionschedule` (
  `date` DATE NOT NULL,
  `brew` VARCHAR(255) NULL,
  `fv` VARCHAR(255) NULL,
  `yst` VARCHAR(255) NULL,
  `transfer` VARCHAR(255) NULL,
  `fuge` VARCHAR(255) NULL,
  `clean` VARCHAR(255) NULL,
  `keg` VARCHAR(255) NULL,
 `bottle` VARCHAR(255) NULL,
 `can` VARCHAR(255) NULL,
  PRIMARY KEY (`date`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `account` VALUES ('roosevelt', '403-999-1111', 'address1');
INSERT INTO `account` VALUES ('ship n anchor', '403-999-1112', 'address2');
INSERT INTO `account` VALUES ('liquor depot', '403-999-1113', 'address3');
INSERT INTO `account` VALUES ('test', '403-999-1114', 'address4');
INSERT INTO `account` VALUES ('test2', '403-999-1115', 'address5');

/*
-- Query: select * from brewmaterials
LIMIT 0, 1000

-- Date: 2018-02-05 18:50
*/
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('2RowMalt',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('2RowMaltSilo',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('AcidulatedMalt',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Amarillo',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Amber',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Azzaca',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Belma',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('BlackMalt',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('CalciumChloride',1000,'kg','chemical');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('CarastanMalt',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Cascades',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Centennial ',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Chinook',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('ChocolateMalt',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Citra',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('CO2',1000,'kg','gas');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('CorianderSeed',1000,'kg','additives');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('CrispBrownMalt',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('CrispPaleChocolate',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Crystal120',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Crystal40',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Crystal75',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('DextraPils',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('EastKentGolding',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Ella',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('PhosphoricAcid',1000,'kg','chemical');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('FoodGradeOxygen',1000,'kg','gas');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('FrancoBelgesSpecial Aroma',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Fuggles',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Galena',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Gypsum',1000,'kg','chemical');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Hallertaur Blanc',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('LemonPeel',1000,'kg','additives');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('MarisOtter',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('MidnightWheat',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Mosaic',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Mt Hood',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('MunichMalt',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('PremiumPilsen',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Raspberry(Squeeze)',1000,'kg','additives');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('RoastedBarley',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('RSBiscuit',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('RSNewdale',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('RSRoastedBarley',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('RyeMalt',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Saaz',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Simcoe',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('SimpsonsNaked Oats',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('SodiumChloride',1000,'kg','chemical');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Sorachi Ace',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('SpecialB',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('SweetSpanishOrange Peel',1000,'kg','additives');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Tahoma',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Tettanang',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('VictoryMalt',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('ViennaMalt',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Waimea',1000,'kg','hops');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('WeyermannCaramunich III',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('WheatMalt',1000,'kg','malt');
INSERT INTO `brewmaterials` (`name`,`qty`,`units`,`type`) VALUES ('Willamette',1000,'kg','hops');

/*
-- Query: SELECT * FROM brewery.employee
LIMIT 0, 1000

-- Date: 2018-01-29 17:00
*/
INSERT INTO `employee` (`empId`,`firstName`,`lastName`,`password`,`email`,`roleId`,`isActive`,`resetPasswordUUID`) VALUES (1,'Matt','Davis','password','matt.davis@edu.sait.ca',1,1,NULL);
INSERT INTO `employee` (`empId`,`firstName`,`lastName`,`password`,`email`,`roleId`,`isActive`,`resetPasswordUUID`) VALUES (2,'Martin','Czerwinski','password','martin.czerwinski@edu.sait.ca',1,1,NULL);
INSERT INTO `employee` (`empId`,`firstName`,`lastName`,`password`,`email`,`roleId`,`isActive`,`resetPasswordUUID`) VALUES (3,'Jesse','Trieu','password','jessie.trieu@edu.sait.ca',2,1,NULL);
INSERT INTO `employee` (`empId`,`firstName`,`lastName`,`password`,`email`,`roleId`,`isActive`,`resetPasswordUUID`) VALUES (4,'Huy','Le','Password','huy.le@edu.sait.ca',1,1,NULL);
INSERT INTO `employee` (`empId`,`firstName`,`lastName`,`password`,`email`,`roleId`,`isActive`,`resetPasswordUUID`) VALUES (5,'Keegan','Evans','password','keegan.evans@edu.sait.ca',1,1,NULL);

/*
-- Query: select * from fv
LIMIT 0, 1000

-- Date: 2018-02-05 18:17
*/
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (1,2000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (2,2000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (3,2000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (4,2000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (5,2000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (6,2000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (7,9000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (8,9000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (9,9000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (10,9000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (11,9000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (12,4000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (13,4000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (14,4000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (15,4000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (16,4000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (17,4000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (18,4000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (19,9000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (20,9000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (21,9000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (22,9000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (23,9000,0,0,0,0,'','');
INSERT INTO `fv` (`fvId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (24,9000,0,0,0,0,'','');

/*
-- Query: SELECT * from productionmaterial
LIMIT 0, 1000

-- Date: 2018-01-31 12:33
*/
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('473mlCans-ReservoirPigsPilsner',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('473mlCansBlacksmith',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('473mlCansBlonde',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('473mlCansSqueeze',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('650mlBottlesBeachcomber',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('650mlBottlesSenator',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('AluminumCanEnd',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Blackgrowlercaps',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('BottleTrays',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('CanTrays',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(12Pack)Blacksmith',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(12Pack)Blonde',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(12Pack)SummerVariety',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(12Pack)WinterVariety',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Blacksmith',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Blonde',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Enigma',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Maiden',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Neighbour',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Squeeze',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Wit',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Crowns',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('HotMeltAdhesive',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCapsBlack',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCapsGreen',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCapStickers',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCapsWhite',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCapsYellow',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsBarnacle',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsBeachcomber',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsBlacksmith',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsBlank',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsBlonde',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsEnigma',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsHolyGrail',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsMaiden',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsNeighbor',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsSqueeze',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsWit',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('LabelGlue',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Blacksmith)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(BlacksmithMC)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Blonde)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(BlondeMC)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Bobby)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(BobbyMC)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Maiden)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Neighbor)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(NeighborMC)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Squeeze)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Wit)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('PrivateMouldBottles',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('QuadPakCanHandles',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('ShippingCartons',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('VillageGrowlers',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('WhiteGrowlerCaps',10000);

/*
-- Query: select * from sv
LIMIT 0, 1000

-- Date: 2018-02-05 18:17
*/
INSERT INTO `sv` (`svId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (1,2000,100,0,0,0,'','');
INSERT INTO `sv` (`svId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (2,2000,200,0,0,0,'','');
INSERT INTO `sv` (`svId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (3,4000,300,0,0,0,'','');
INSERT INTO `sv` (`svId`,`capacity`,`volume`,`brew1`,`brew2`,`brew3`,`brand`,`status`) VALUES (4,9000,400,0,0,0,'','');

/*
-- Query: select * from productionschedule
LIMIT 0, 1000

-- Date: 2018-03-29 12:50
*/
INSERT INTO `productionschedule` (`date`,`brew`,`fv`,`yst`,`transfer`,`fuge`,`clean`,`keg`,`bottle`,`can`) VALUES ('2018-03-05','','','','','','','','','');
INSERT INTO `productionschedule` (`date`,`brew`,`fv`,`yst`,`transfer`,`fuge`,`clean`,`keg`,`bottle`,`can`) VALUES ('2018-03-06','','','','','','','','','');
INSERT INTO `productionschedule` (`date`,`brew`,`fv`,`yst`,`transfer`,`fuge`,`clean`,`keg`,`bottle`,`can`) VALUES ('2018-03-07','','','','','','','','','');
INSERT INTO `productionschedule` (`date`,`brew`,`fv`,`yst`,`transfer`,`fuge`,`clean`,`keg`,`bottle`,`can`) VALUES ('2018-03-08','','','','','','','','','');
INSERT INTO `productionschedule` (`date`,`brew`,`fv`,`yst`,`transfer`,`fuge`,`clean`,`keg`,`bottle`,`can`) VALUES ('2018-03-09','','','','','','','','','');


DROP TRIGGER IF EXISTS `brewery`.`brew_BEFORE_INSERT`;

DELIMITER $$
USE `brewery`$$
CREATE DEFINER=`root`@`localhost` TRIGGER `brewery`.`brew_BEFORE_INSERT` BEFORE INSERT ON `brew` FOR EACH ROW
BEGIN

  DECLARE matQty FLOAT DEFAULT 0;
  DECLARE typeName VARCHAR(25) DEFAULT "";
  DECLARE brewName VARCHAR(25) DEFAULT "";
  DECLARE done INT DEFAULT FALSE;
  DECLARE cur1 CURSOR FOR SELECT *
  FROM recipematerials;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
  
  
  
 
 

  OPEN cur1;
  

  read_loop: LOOP
    FETCH cur1 INTO matQty,typeName,brewName;
    IF done THEN
      LEAVE read_loop;
      END IF;
    
    if(NEW.recipeName = typeName) THEN
        UPDATE brewmaterials
            SET qty = qty-matQty
                WHERE name = brewName;
                END if;
                
                
           
    
  END LOOP;

  CLOSE cur1;

END$$
DELIMITER ;

DROP TRIGGER IF EXISTS `brewery`.`production_BEFORE_INSERT`;

DELIMITER $$
USE `brewery`$$
CREATE DEFINER=`root`@`localhost` TRIGGER `brewery`.`production_BEFORE_INSERT` BEFORE INSERT ON `production` FOR EACH ROW
BEGIN
  
  DECLARE prodQty DOUBLE DEFAULT 0;
  DECLARE matQty DOUBLE DEFAULT 0;
  DECLARE prodName VARCHAR(25) DEFAULT "";
  DECLARE matName VARCHAR(25) DEFAULT "";
  DECLARE done INT DEFAULT FALSE;
  DECLARE cur1 CURSOR FOR SELECT *
  FROM productionmaterialusage;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
  
  SET prodQty = New.quantity;
  
  UPDATE sv
    SET volume = NEW.finishedSvVolume
        WHERE svId = NEW.svNum;

  UPDATE finishedproduct
    SET qty = qty+prodQty
        WHERE productName = NEW.productionType;

  OPEN cur1;
  

  read_loop: LOOP
    FETCH cur1 INTO matQty,prodName,matName;
    IF done THEN
      LEAVE read_loop;
      END IF;
    
    IF(NEW.productionType = prodName) THEN
        UPDATE productionmaterial
            SET qty = qty-matQty*prodQty
                WHERE name = matName;

    END IF;

  END LOOP;

  CLOSE cur1;

END$$
DELIMITER ;

DROP TRIGGER IF EXISTS `brewery`.`recipe_BEFORE_INSERT`;

DELIMITER $$
USE `brewery`$$
CREATE DEFINER=`root`@`localhost` TRIGGER `brewery`.`recipe_BEFORE_INSERT` BEFORE INSERT ON `recipe` FOR EACH ROW
BEGIN


  
if(NEW.gypsumAmt <> 0)
    THEN
        INSERT INTO recipematerials
            (qty,recipeName,brewMaterialsName)
                VALUES(NEW.gypsumAmt, NEW.recipeName, 'Gypsum');
END if;

if(NEW.calciumChlorideAmt <> 0)
    THEN
        INSERT INTO recipematerials
            (qty,recipeName,brewMaterialsName)
                VALUES(NEW.calciumChlorideAmt, NEW.recipeName, 'CalciumChloride');

END if;

if(NEW.sodiumChlorideAmt <> 0)
    THEN
        INSERT INTO recipematerials
            (qty,recipeName,brewMaterialsName)
                VALUES(NEW.sodiumChlorideAmt, NEW.recipeName, 'SodiumChloride');

END if;

if(NEW.phosphAcidAmt <> 0)
    THEN
        INSERT INTO recipematerials
            (qty,recipeName,brewMaterialsName)
                VALUES(NEW.phosphAcidAmt, NEW.recipeName, 'PhosphoricAcid');

END if;

if(NEW.firstHop IS NOT NULL)
    THEN
        INSERT INTO recipematerials
            (qty,recipeName,brewMaterialsName)
                VALUES(NEW.firstHopAmt, NEW.recipeName, NEW.firstHop);
end if;


if(NEW.secondHop IS NOT NULL)
    THEN
        INSERT INTO recipematerials
            (qty,recipeName,brewMaterialsName)
                VALUES(NEW.secondHopAmt, NEW.recipeName, NEW.secondHop);
end if;

INSERT INTO recipematerials
            (qty,recipeName,brewMaterialsName)
                VALUES(NEW.baseMaltAmt, NEW.recipeName, NEW.baseMalt);



if(NEW.thirdHop IS NOT NULL)
    THEN
        INSERT INTO recipematerials
            (qty,recipeName,brewMaterialsName)
                VALUES(NEW.thirdHopAmt, NEW.recipeName, NEW.thirdHop);

End if;

if(NEW.secondMalt IS NOT NULL)
    THEN
        INSERT INTO recipematerials
            (qty,recipeName,brewMaterialsName)
                VALUES(NEW.secondMaltAmt, NEW.recipeName, NEW.secondMalt);

End if;
        
if(NEW.thirdMalt IS NOT NULL)
    THEN
        INSERT INTO recipematerials
            (qty,recipeName,brewMaterialsName)
                VALUES(NEW.thirdMaltAmt, NEW.recipeName, NEW.thirdMalt);

End if;
  
if(NEW.fourthMalt IS NOT NULL)
    THEN
        INSERT INTO recipematerials
            (qty,recipeName,brewMaterialsName)
                VALUES(NEW.fourthMaltAmt, NEW.recipeName, NEW.fourthMalt);

End if;


END$$
DELIMITER ;



