/*
-- Query: SELECT * from productionmaterial
LIMIT 0, 1000

-- Date: 2018-01-31 12:33
*/
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('473mlCans-ReservoirPigsPilsner',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('473mlCansBlacksmith',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('473mlCansBlonde',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('473mlCansSqueeze',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('650mlBottlesBeachcomber',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('650mlBottlesSenator',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('AluminumCanEnd',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Blackgrowlercaps',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('BottleTrays',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('CanTrays',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(12Pack)Blacksmith',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(12Pack)Blonde',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(12Pack)SummerVariety',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(12Pack)WinterVariety',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Blacksmith',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Blonde',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Enigma',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Maiden',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Neighbour',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Squeeze',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Cartons(6Pack)Wit',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Crowns',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('HotMeltAdhesive',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCapsBlack',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCapsGreen',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCapStickers',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCapsWhite',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCapsYellow',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsBarnacle',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsBeachcomber',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsBlacksmith',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsBlank',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsBlonde',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsEnigma',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsHolyGrail',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsMaiden',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsNeighbor',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsSqueeze',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('KegCollarsWit',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('LabelGlue',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Blacksmith)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(BlacksmithMC)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Blonde)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(BlondeMC)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Bobby)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(BobbyMC)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Maiden)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Neighbor)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(NeighborMC)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Squeeze)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('Labels(Wit)',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('PrivateMouldBottles',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('QuadPakCanHandles',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('ShippingCartons',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('VillageGrowlers',10000);
INSERT INTO `productionmaterial` (`name`,`qty`) VALUES ('WhiteGrowlerCaps',10000);
