INSERT INTO `product` VALUES ('blonde 6 pack (flats)', 12, 1);
INSERT INTO `product` VALUES ('blonde 12 pack (flats)', 4, 1);
INSERT INTO `product` VALUES ('blacksmith', '2018-02-02', 3, 1);
INSERT INTO `product` VALUES ('wit', 2, 1);
INSERT INTO `product` VALUES ('bobby',3, 1);
INSERT INTO `product` VALUES ('beachcomber', 3, 1);
INSERT INTO `product` VALUES ('neighbour', 3, 1);
INSERT INTO `product` VALUES ('gardener', 3, 1);
INSERT INTO `product` VALUES ('blonde 6 pack (flats)', 12, 2);
INSERT INTO `product` VALUES ('blonde 12 pack (flats)', 4, 2);
INSERT INTO `product` VALUES ('blacksmith', '2018-02-02', 3, 2);
INSERT INTO `product` VALUES ('wit', 2, 2);
INSERT INTO `product` VALUES ('bobby',3, 2);
INSERT INTO `product` VALUES ('beachcomber', 3, 2);
INSERT INTO `product` VALUES ('neighbour', 3, 2);
INSERT INTO `product` VALUES ('gardener', 3, 2);
INSERT INTO `product` VALUES ('blonde 6 pack (flats)', 12, 3);
INSERT INTO `product` VALUES ('blonde 12 pack (flats)', 4, 3);
INSERT INTO `product` VALUES ('blacksmith', '2018-02-02', 3, 3);
INSERT INTO `product` VALUES ('wit', 2, 3);
INSERT INTO `product` VALUES ('bobby',3, 3);
INSERT INTO `product` VALUES ('beachcomber', 3, 3);
INSERT INTO `product` VALUES ('neighbour', 3, 3);
INSERT INTO `product` VALUES ('gardener', 3, 3);
INSERT INTO `product` VALUES ('blonde 6 pack (flats)', 12, 4);
INSERT INTO `product` VALUES ('blonde 12 pack (flats)', 4, 4);
INSERT INTO `product` VALUES ('blacksmith', '2018-02-02', 3, 4);
INSERT INTO `product` VALUES ('wit', 2, 4);
INSERT INTO `product` VALUES ('bobby',3, 4);
INSERT INTO `product` VALUES ('beachcomber', 3, 4);
INSERT INTO `product` VALUES ('neighbour', 3, 4);
INSERT INTO `product` VALUES ('gardener', 3, 4);
INSERT INTO `product` VALUES ('blonde 6 pack (flats)', 12, 5);
INSERT INTO `product` VALUES ('blonde 12 pack (flats)', 4, 5);
INSERT INTO `product` VALUES ('blacksmith', '2018-02-02', 3, 5);
INSERT INTO `product` VALUES ('wit', 2, 5);
INSERT INTO `product` VALUES ('bobby',3, 5);
INSERT INTO `product` VALUES ('beachcomber', 3, 5);
INSERT INTO `product` VALUES ('neighbour', 3, 5);
INSERT INTO `product` VALUES ('gardener', 3, 5);
INSERT INTO `product` VALUES ('blonde 6 pack (flats)', 12, 6);
INSERT INTO `product` VALUES ('blonde 12 pack (flats)', 4, 6);
INSERT INTO `product` VALUES ('blacksmith', '2018-02-02', 3, 6);
INSERT INTO `product` VALUES ('wit', 2, 6);
INSERT INTO `product` VALUES ('bobby',3, 6);
INSERT INTO `product` VALUES ('beachcomber', 3, 6);
INSERT INTO `product` VALUES ('neighbour', 3, 6);
INSERT INTO `product` VALUES ('gardener', 3, 6);
INSERT INTO `product` VALUES ('blonde 6 pack (flats)', 12, 7);
INSERT INTO `product` VALUES ('blonde 12 pack (flats)', 4, 7);
INSERT INTO `product` VALUES ('blacksmith', '2018-02-02', 3, 7);
INSERT INTO `product` VALUES ('wit', 2, 7);
INSERT INTO `product` VALUES ('bobby',3, 7);
INSERT INTO `product` VALUES ('beachcomber', 3, 7);
INSERT INTO `product` VALUES ('neighbour', 3, 7);
INSERT INTO `product` VALUES ('gardener', 3, 7);
