/*
-- Query: select * from recipe
LIMIT 0, 1000

-- Date: 2018-02-05 19:18
*/
INSERT INTO `recipe` (`recipeName`,`mashInTemp`,`mashInTime`,`mashWaterVolume`,`restTime`,`raiseToTemp`,`inTime`,`totalMashTime`,`underletLitres`,`rest`,`vorlaufTime`,`firstWortGrav`,`runOffTime`,`spargVol`,`spargTemp`,`lastRunningsGrav`,`kettleFullVol`,`kettleFullGrav`,`boilTime`,`strikeOutVol`,`strikeOutGrav`,`whirlPoolTime`,`coolInTemp`,`oxygenRate`,`gypsumAmt`,`calciumChlorideAmt`,`sodiumChlorideAmt`,`phosphAcidAmt`,`firstHop`,`firstHopAmt`,`secondHop`,`secondHopAmt`,`thirdHop`,`thirdHopAmt`,`baseMalt`,`baseMaltAmt`,`secondMalt`,`secondMaltAmt`,`thirdMalt`,`thirdMaltAmt`,`fourthMalt`,`fourthMaltAmt`) VALUES ('Blacksmith',70,40,12,30,78,10,80,1,5,15,20,60,2,78,18,26,22,120,23,23.5,20,18,6,200,250,200,150,'Belma','2','Amarillo','3','Citra','3.4','2RowMalt','300','BlackMalt','30','','','','');
INSERT INTO `recipe` (`recipeName`,`mashInTemp`,`mashInTime`,`mashWaterVolume`,`restTime`,`raiseToTemp`,`inTime`,`totalMashTime`,`underletLitres`,`rest`,`vorlaufTime`,`firstWortGrav`,`runOffTime`,`spargVol`,`spargTemp`,`lastRunningsGrav`,`kettleFullVol`,`kettleFullGrav`,`boilTime`,`strikeOutVol`,`strikeOutGrav`,`whirlPoolTime`,`coolInTemp`,`oxygenRate`,`gypsumAmt`,`calciumChlorideAmt`,`sodiumChlorideAmt`,`phosphAcidAmt`,`firstHop`,`firstHopAmt`,`secondHop`,`secondHopAmt`,`thirdHop`,`thirdHopAmt`,`baseMalt`,`baseMaltAmt`,`secondMalt`,`secondMaltAmt`,`thirdMalt`,`thirdMaltAmt`,`fourthMalt`,`fourthMaltAmt`) VALUES ('Blonde',70,40,12,30,78,10,80,1,5,15,20,60,2,78,18,26,22,120,23,23.5,20,18,6,200,250,200,150,'Cascades','2.5','Chinook','2','Citra','2','2RowMalt','350','Crystal120','20','','','','');
INSERT INTO `recipe` (`recipeName`,`mashInTemp`,`mashInTime`,`mashWaterVolume`,`restTime`,`raiseToTemp`,`inTime`,`totalMashTime`,`underletLitres`,`rest`,`vorlaufTime`,`firstWortGrav`,`runOffTime`,`spargVol`,`spargTemp`,`lastRunningsGrav`,`kettleFullVol`,`kettleFullGrav`,`boilTime`,`strikeOutVol`,`strikeOutGrav`,`whirlPoolTime`,`coolInTemp`,`oxygenRate`,`gypsumAmt`,`calciumChlorideAmt`,`sodiumChlorideAmt`,`phosphAcidAmt`,`firstHop`,`firstHopAmt`,`secondHop`,`secondHopAmt`,`thirdHop`,`thirdHopAmt`,`baseMalt`,`baseMaltAmt`,`secondMalt`,`secondMaltAmt`,`thirdMalt`,`thirdMaltAmt`,`fourthMalt`,`fourthMaltAmt`) VALUES ('Wit',70,40,12,30,78,10,80,1,5,15,20,60,2,78,18,26,22,120,23,23.5,20,18,6,200,250,200,150,'Belma','2','Amarillo','2.4','Citra','2','2RowMalt','325','BlackMalt','50','','','','');
